plugins {
    id 'com.android.application'
}

android {
    namespace 'it.edilmilan.clienti'
    compileSdk 35

    defaultConfig {
        applicationId 'it.edilmilan.clienti'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '1.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
